# Generated by Django 2.0.2 on 2018-02-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_module_pcb_plate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pcb',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='plate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'managed': False},
        ),
    ]
