# Generated by Django 2.0.2 on 2018-02-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180218_1213'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table='module',
        ),
        migrations.AlterModelTable(
            name='pcb',
            table='pcb',
        ),
        migrations.AlterModelTable(
            name='plate',
            table='plate',
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='sensor',
        ),
    ]
