# Generated by Django 2.0.2 on 2018-02-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180218_1214'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pcb',
            table=None,
        ),
        migrations.AlterModelTable(
            name='plate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sensor',
            table=None,
        ),
    ]
