# Generated by Django 2.0.2 on 2018-02-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180218_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pcb',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={},
        ),
    ]
