# Generated by Django 2.0.2 on 2018-02-18 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180218_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pcb',
            name='type',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='type',
        ),
        migrations.AddField(
            model_name='module',
            name='pcb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Pcb'),
        ),
        migrations.AddField(
            model_name='module',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Plate'),
        ),
        migrations.AddField(
            model_name='module',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Sensor'),
        ),
        migrations.AddField(
            model_name='module',
            name='thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcb',
            name='bonded_skirocs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcb',
            name='channels',
            field=models.IntegerField(default=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcb',
            name='flatness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcb',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pcb',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pcb',
            name='size',
            field=models.FloatField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcb',
            name='thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='flatness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='material',
            field=models.CharField(default='CuW', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plate',
            name='max_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='min_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='nom_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='size',
            field=models.FloatField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='channels',
            field=models.IntegerField(default=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='manufacturer',
            field=models.CharField(default='Hamamatsu', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='size',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
