# Generated by Django 2.0.1 on 2018-02-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180218_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='kapton',
            field=models.CharField(default='y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='pcb_error_theta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='pcb_error_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='pcb_error_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='position',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='sensor_error_theta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='sensor_error_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='sensor_error_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='tray_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
