# Generated by Django 2.0.1 on 2018-02-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180218_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='tray_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
