# Generated by Django 2.0.2 on 2018-02-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180218_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='pcb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Pcb'),
        ),
        migrations.AlterField(
            model_name='module',
            name='plate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Plate'),
        ),
        migrations.AlterField(
            model_name='module',
            name='sensor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Sensor'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
