# Generated by Django 2.0.2 on 2018-02-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180218_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipped_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_table_name', models.CharField(choices=[('Module', 'Module'), ('Sensor', 'Sensor'), ('Pcb', 'PCB'), ('Plate', 'Plates')], max_length=20)),
                ('shipment_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Shipment')),
            ],
        ),
    ]
