# Generated by Django 2.0.2 on 2018-02-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_shipment_shipped_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipped_item',
            old_name='shipment_id',
            new_name='shipment',
        ),
        migrations.AddField(
            model_name='shipped_item',
            name='item_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
