# Generated by Django 2.0.2 on 2018-02-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20180218_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipped_item',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Shipment'),
        ),
    ]
