# Generated by Django 2.0.1 on 2018-03-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='table',
            field=models.CharField(default='sensor', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='table_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
