# Generated by Django 2.0.2 on 2018-03-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_module_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='identifier',
        ),
    ]
